### ISSUE TITLE
Relative UI links

### ISSUE THREAD

**Issue by devinrsmith** [deephaven/web-client-ui#1070]
Some use cases, namely proxying based on a fixed prefix, would greatly benefit if the UI was built using relative links. @mofojed has helped me get a PoC up and running, and it works beautifully.

See https://github.com/deephaven/web-client-ui/tree/relative-base-url

This is not a full solution (as notebooks don't work), but demonstrates that `<prefix>/ide/` works.

I'm happy to help a dev get up a simple, or complex, reverse proxy setup to validate any fix.

Note: it's not possible to use different prefixes w/ gRPC, so for muli-instance proxying, the proxy needs to key off some other kind of information. I was able to leverage the `Referer` header to proxy gRPC appropriately in the case of multiple DHC instances.

A simple setup might look like:

docker-compose.yml:
```yml
version: '3'

name: deephaven-caddy

services:
  deephaven:
    image: <deephaven-server-with-relative-ui-link-support>

  reverse-proxy:
    image: caddy:2.6.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
```

Caddyfile:
```
test.localhost {
    handle /foo/* {
        uri strip_prefix /foo
        reverse_proxy {
            to h2c://deephaven:10000
        }
    }
    reverse_proxy {
        to h2c://deephaven:10000
    }
}
```

Then ensuring that https://test.localhost/foo/ide/ works.
